# coding: utf-8

"""
    Gluster Management API

    Gluster Management APIs  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import glusterapi
from glusterapi.api.client import Client  # noqa: E501
from glusterapi.rest import ApiException


class TestClient(unittest.TestCase):
    """Client unit test stubs"""

    def setUp(self):
        self.api = glusterapi.api.client.Client()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_peer(self):
        """Test case for add_peer

        """
        pass

    def test_delete_peer(self):
        """Test case for delete_peer

        """
        pass

    def test_edit_peer(self):
        """Test case for edit_peer

        """
        pass

    def test_get_peer(self):
        """Test case for get_peer

        """
        pass

    def test_get_peers(self):
        """Test case for get_peers

        """
        pass

    def test_volume_create(self):
        """Test case for volume_create

        """
        pass

    def test_volume_info(self):
        """Test case for volume_info

        """
        pass

    def test_volume_start(self):
        """Test case for volume_start

        """
        pass

    def test_volume_stop(self):
        """Test case for volume_stop

        """
        pass


if __name__ == '__main__':
    unittest.main()
