# coding: utf-8

"""
    Gluster Management API

    Gluster Management APIs  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class FileGfid(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'chardata': 'str',
        'gfid': 'str'
    }

    attribute_map = {
        'chardata': 'chardata',
        'gfid': 'gfid'
    }

    def __init__(self, chardata=None, gfid=None):  # noqa: E501
        """FileGfid - a model defined in OpenAPI"""  # noqa: E501

        self._chardata = None
        self._gfid = None
        self.discriminator = None

        if chardata is not None:
            self.chardata = chardata
        if gfid is not None:
            self.gfid = gfid

    @property
    def chardata(self):
        """Gets the chardata of this FileGfid.  # noqa: E501


        :return: The chardata of this FileGfid.  # noqa: E501
        :rtype: str
        """
        return self._chardata

    @chardata.setter
    def chardata(self, chardata):
        """Sets the chardata of this FileGfid.


        :param chardata: The chardata of this FileGfid.  # noqa: E501
        :type: str
        """

        self._chardata = chardata

    @property
    def gfid(self):
        """Gets the gfid of this FileGfid.  # noqa: E501


        :return: The gfid of this FileGfid.  # noqa: E501
        :rtype: str
        """
        return self._gfid

    @gfid.setter
    def gfid(self, gfid):
        """Sets the gfid of this FileGfid.


        :param gfid: The gfid of this FileGfid.  # noqa: E501
        :type: str
        """

        self._gfid = gfid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FileGfid):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
