# coding: utf-8

"""
    Gluster Management API

    Gluster Management APIs  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.brick_heal import BrickHeal  # noqa: E501
from openapi_client.rest import ApiException


class TestBrickHeal(unittest.TestCase):
    """BrickHeal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBrickHeal(self):
        """Test BrickHeal"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.brick_heal.BrickHeal()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
