# coding: utf-8

"""
    Gluster Management API

    Gluster Management APIs  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bitrot_disable(self):
        """Test case for bitrot_disable

        """
        pass

    def test_bitrot_enable(self):
        """Test case for bitrot_enable

        """
        pass

    def test_bitrot_scrub_ondemand(self):
        """Test case for bitrot_scrub_ondemand

        """
        pass

    def test_bitrot_scrub_status(self):
        """Test case for bitrot_scrub_status

        """
        pass

    def test_self_heal_info(self):
        """Test case for self_heal_info

        """
        pass

    def test_self_heal_info2(self):
        """Test case for self_heal_info2

        """
        pass


if __name__ == '__main__':
    unittest.main()
