# coding: utf-8

"""
    Gluster Management API

    Gluster Management APIs  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import glusterapi
from glusterapi.models.add import Add  # noqa: E501
from glusterapi.rest import ApiException


class TestAdd(unittest.TestCase):
    """Add unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdd(self):
        """Test Add"""
        # FIXME: construct object with mandatory attributes with example values
        # model = glusterapi.models.add.Add()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
