# coding: utf-8

"""
    Gluster Management API

    Gluster Management APIs  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import glusterapi
from glusterapi.models.brick2 import Brick2  # noqa: E501
from glusterapi.rest import ApiException


class TestBrick2(unittest.TestCase):
    """Brick2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBrick2(self):
        """Test Brick2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = glusterapi.models.brick2.Brick2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
