# coding: utf-8

"""
    Gluster Management API

    Gluster Management APIs  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class SshPublicKey(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'peerid': 'str',
        'gsyncd': 'str',
        'tar': 'str'
    }

    attribute_map = {
        'peerid': 'peerid',
        'gsyncd': 'gsyncd',
        'tar': 'tar'
    }

    def __init__(self, peerid=None, gsyncd=None, tar=None):  # noqa: E501
        """SshPublicKey - a model defined in OpenAPI"""  # noqa: E501

        self._peerid = None
        self._gsyncd = None
        self._tar = None
        self.discriminator = None

        if peerid is not None:
            self.peerid = peerid
        if gsyncd is not None:
            self.gsyncd = gsyncd
        if tar is not None:
            self.tar = tar

    @property
    def peerid(self):
        """Gets the peerid of this SshPublicKey.  # noqa: E501


        :return: The peerid of this SshPublicKey.  # noqa: E501
        :rtype: str
        """
        return self._peerid

    @peerid.setter
    def peerid(self, peerid):
        """Sets the peerid of this SshPublicKey.


        :param peerid: The peerid of this SshPublicKey.  # noqa: E501
        :type: str
        """

        self._peerid = peerid

    @property
    def gsyncd(self):
        """Gets the gsyncd of this SshPublicKey.  # noqa: E501


        :return: The gsyncd of this SshPublicKey.  # noqa: E501
        :rtype: str
        """
        return self._gsyncd

    @gsyncd.setter
    def gsyncd(self, gsyncd):
        """Sets the gsyncd of this SshPublicKey.


        :param gsyncd: The gsyncd of this SshPublicKey.  # noqa: E501
        :type: str
        """

        self._gsyncd = gsyncd

    @property
    def tar(self):
        """Gets the tar of this SshPublicKey.  # noqa: E501


        :return: The tar of this SshPublicKey.  # noqa: E501
        :rtype: str
        """
        return self._tar

    @tar.setter
    def tar(self, tar):
        """Sets the tar of this SshPublicKey.


        :param tar: The tar of this SshPublicKey.  # noqa: E501
        :type: str
        """

        self._tar = tar

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SshPublicKey):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
