# coding: utf-8

"""
    Gluster Management API

    Gluster Management APIs  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class SnapBrickStatus(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'brick': 'BrickStatus',
        'lvs_data': 'LvsData'
    }

    attribute_map = {
        'brick': 'brick',
        'lvs_data': 'lvs-data'
    }

    def __init__(self, brick=None, lvs_data=None):  # noqa: E501
        """SnapBrickStatus - a model defined in OpenAPI"""  # noqa: E501

        self._brick = None
        self._lvs_data = None
        self.discriminator = None

        if brick is not None:
            self.brick = brick
        if lvs_data is not None:
            self.lvs_data = lvs_data

    @property
    def brick(self):
        """Gets the brick of this SnapBrickStatus.  # noqa: E501


        :return: The brick of this SnapBrickStatus.  # noqa: E501
        :rtype: BrickStatus
        """
        return self._brick

    @brick.setter
    def brick(self, brick):
        """Sets the brick of this SnapBrickStatus.


        :param brick: The brick of this SnapBrickStatus.  # noqa: E501
        :type: BrickStatus
        """

        self._brick = brick

    @property
    def lvs_data(self):
        """Gets the lvs_data of this SnapBrickStatus.  # noqa: E501


        :return: The lvs_data of this SnapBrickStatus.  # noqa: E501
        :rtype: LvsData
        """
        return self._lvs_data

    @lvs_data.setter
    def lvs_data(self, lvs_data):
        """Sets the lvs_data of this SnapBrickStatus.


        :param lvs_data: The lvs_data of this SnapBrickStatus.  # noqa: E501
        :type: LvsData
        """

        self._lvs_data = lvs_data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SnapBrickStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
