# coding: utf-8

"""
    Gluster Management API

    Gluster Management APIs  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_snapshot_activate(self):
        """Test case for snapshot_activate

        """
        pass

    def test_snapshot_clone(self):
        """Test case for snapshot_clone

        """
        pass

    def test_snapshot_create(self):
        """Test case for snapshot_create

        """
        pass

    def test_snapshot_deactivate(self):
        """Test case for snapshot_deactivate

        """
        pass

    def test_snapshot_delete(self):
        """Test case for snapshot_delete

        """
        pass

    def test_snapshot_info(self):
        """Test case for snapshot_info

        """
        pass

    def test_snapshot_list_all(self):
        """Test case for snapshot_list_all

        """
        pass

    def test_snapshot_restore(self):
        """Test case for snapshot_restore

        """
        pass

    def test_snapshot_status(self):
        """Test case for snapshot_status

        """
        pass


if __name__ == '__main__':
    unittest.main()
