# coding: utf-8

"""
    Gluster Management API

    Gluster Management APIs  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.size_info import SizeInfo  # noqa: E501
from openapi_client.rest import ApiException


class TestSizeInfo(unittest.TestCase):
    """SizeInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSizeInfo(self):
        """Test SizeInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.size_info.SizeInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
