# coding: utf-8

"""
    Gluster Management API

    Gluster Management APIs  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.option2 import Option2  # noqa: E501
from openapi_client.rest import ApiException


class TestOption2(unittest.TestCase):
    """Option2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOption2(self):
        """Test Option2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.option2.Option2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
