# coding: utf-8

"""
    Gluster Management API

    Gluster Management APIs  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.remotehost import Remotehost  # noqa: E501
from openapi_client.rest import ApiException


class TestRemotehost(unittest.TestCase):
    """Remotehost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRemotehost(self):
        """Test Remotehost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.remotehost.Remotehost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
