# coding: utf-8

"""
    Gluster Management API

    Gluster Management APIs  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.remotehost2 import Remotehost2  # noqa: E501
from openapi_client.rest import ApiException


class TestRemotehost2(unittest.TestCase):
    """Remotehost2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRemotehost2(self):
        """Test Remotehost2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.remotehost2.Remotehost2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
