# coding: utf-8

"""
    Gluster Management API

    Gluster Management APIs  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_geo_replication_config_get(self):
        """Test case for geo_replication_config_get

        """
        pass

    def test_geo_replication_config_reset(self):
        """Test case for geo_replication_config_reset

        """
        pass

    def test_geo_replication_config_set(self):
        """Test case for geo_replication_config_set

        """
        pass

    def test_geo_replication_create(self):
        """Test case for geo_replication_create

        """
        pass

    def test_geo_replication_delete(self):
        """Test case for geo_replication_delete

        """
        pass

    def test_geo_replication_pause(self):
        """Test case for geo_replication_pause

        """
        pass

    def test_geo_replication_resume(self):
        """Test case for geo_replication_resume

        """
        pass

    def test_geo_replication_ssh_key_generate(self):
        """Test case for geo_replication_ssh_key_generate

        """
        pass

    def test_geo_replication_ssh_key_get(self):
        """Test case for geo_replication_ssh_key_get

        """
        pass

    def test_geo_replication_ssh_key_push(self):
        """Test case for geo_replication_ssh_key_push

        """
        pass

    def test_geo_replication_start(self):
        """Test case for geo_replication_start

        """
        pass

    def test_geo_replication_status(self):
        """Test case for geo_replication_status

        """
        pass

    def test_geo_replication_status_list(self):
        """Test case for geo_replication_status_list

        """
        pass

    def test_geo_replication_stop(self):
        """Test case for geo_replication_stop

        """
        pass


if __name__ == '__main__':
    unittest.main()
